### ISSUE TITLE
Magisk Manager (80d834fb) (215)

### ISSUE THREAD

**Issue by lucenera** [diareuse/Magisk#10]
There are functional regressions:
1: the download page sometimes shows only a list of some module not installed and nothing more. Sometimes it shows some modules installed, but not all;
2: even if fingerprint recognition is active, it does not work. Closing the app and reopening, the option is unchecked;
3: the superuser settings do not work, whatever is set, the settings remain at the default settings.

**Comment by diareuse** [comment]
Thanks for reporting these issues.

1) I've never personally encountered this and no efforts have been made to fix this, yet. It's suspected GitHub's throttling behavior, but wouldn't put my hand on that.
2) Using the latest canary I don't seem to have this issue. In case you do, would you mind deleting app data, try it again and then report back with the result?
3) Queries for policies were reportedly f-ed up as well, this should be all fixed in the latest canary.

**Comment by lucenera** [comment]
The errors of the previous version have disappeared: 1) however, the problem of language returned, which, even if imposed on English, remains that of the system;  2) the list of apps with superuser is a blank screen.

**Comment by diareuse** [comment]
Both issues should be resolved in an upcoming canary.
